FROM node:22

WORKDIR /usr/src/app

COPY package.json ./
COPY tsconfig.json ./
COPY nodemon.json ./

COPY src ./src
RUN ls -a
RUN npm install --save-dev nodemon ts-node typescript

EXPOSE 3000

CMD ["npm","run","dev"]