version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: dockerfile.dev
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app      # Mount local code into container
      - /usr/src/app/node_modules # Avoid overwriting node_modules
    external_links:
      - mongo
    depends_on:
      - mongo
volumes:
  mongo-data:
    driver: local