apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      # --- FORCE SPREAD CONFIGURATION START ---
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: nest-app
              topologyKey: "kubernetes.io/hostname"
      # --- FORCE SPREAD CONFIGURATION END ---
      containers:
      - name: nest-app
        image: nest-perf-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/perf_db"
        resources:
          requests:
            cpu: "500m"      # Request 0.5 CPU per pod
            memory: "256Mi"
          limits:
            cpu: "1000m"     # Max 1 CPU core per pod
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nest-service
spec:
  type: LoadBalancer
  selector:
    app: nest-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
